// Sven Co-op Map RES file - Poke646 Co-op map
// Map Author:  Mindmotor Studios
// Author Website: http://www.poke646.com/

po_decals.wad
halflife.wad
liquids.wad
models/metalplategibs_dark.mdl
poke646.wad
sound/ambience/breather.wav
sound/ambience/doorpunch.wav
sound/ambience/drips.wav
sound/ambience/pumper.wav
sound/ambience/squitch.wav
sound/ambience/steamjet1.wav
sound/ambience/waterfall1.wav
sound/ambience/waterfall2.wav
sound/ambience/waterfall3.wav
sound/debris/beamstart2.wav
sound/debris/beamstart7.wav
sound/zombie/zo_pain2.wav
sprites/Fexplo1.spr
sprites/lgtning.spr
sprites/poke646/levelchange.spr
sound/poke646/mp3/sewer.mp3
sprites/redflare1.spr
sprites/redflare2.spr
sprites/sdrip1.spr
sprites/wsplash3.spr
sprites/XFlare1.spr
sprites/xsmoke1.spr
sprites/yelflare1.spr
models/poke646/weapons/heaterpipe/v_heaterpipe.mdl
models/poke646/weapons/heaterpipe/w_heaterpipe.mdl
models/poke646/weapons/heaterpipe/p_heaterpipe.mdl
sound/poke646/weapons/heaterpipe/heaterpipe_breathe.wav
sound/poke646/weapons/heaterpipe/heaterpipe_hit1.wav
sound/poke646/weapons/heaterpipe/heaterpipe_hit2.wav
sound/poke646/weapons/heaterpipe/heaterpipe_miss.wav
sprites/poke646/heaterpipe.spr
sprites/poke646/weapon_heaterpipe.txt
models/poke646/weapons/bradnailer/v_bradnailer.mdl
models/poke646/weapons/bradnailer/w_bradnailer.mdl
models/poke646/weapons/bradnailer/p_bradnailer.mdl
sound/poke646/weapons/bradnailer/bradnailer_clipin.wav
sound/poke646/weapons/bradnailer/bradnailer_clipout.wav
sound/poke646/weapons/bradnailer/bradnailer_fire.wav
sprites/poke646/bradnailer.spr
sprites/poke646/weapon_bradnailer.txt
models/poke646/weapons/nailgun/v_nailgun.mdl
models/poke646/weapons/nailgun/w_nailgun.mdl
models/poke646/weapons/nailgun/p_nailgun.mdl
sound/poke646/weapons/nailgun/nailgun_clipin.wav
sound/poke646/weapons/nailgun/nailgun_clipout.wav
sound/poke646/weapons/nailgun/nailgun_fire.wav
sprites/poke646/nailgun.spr
sprites/poke646/weapon_nailgun.txt
models/poke646/weapons/pipebomb/v_pipebomb.mdl
models/poke646/weapons/pipebomb/v_pipebomb_watch.mdl
models/poke646/weapons/pipebomb/w_pipebomb.mdl
models/poke646/weapons/pipebomb/w_pipebombt.mdl
models/poke646/weapons/pipebomb/p_pipebomb.mdl
models/poke646/weapons/pipebomb/p_pipebomb_watch.mdl
sound/poke646/weapons/pipebomb/pipebomb_bounce1.wav
sound/poke646/weapons/pipebomb/pipebomb_bounce2.wav
sound/poke646/weapons/pipebomb/pipebomb_bounce3.wav
sprites/poke646/pipebomb.spr
sprites/poke646/weapon_satchel.txt
models/poke646/items/crossbow_bolt.mdl
models/poke646/items/nail.mdl
models/poke646/items/shotgunshell.mdl
models/poke646/items/w_crossbow_clip.mdl
models/poke646/items/w_medibox.mdl
models/poke646/items/w_nailclip.mdl
models/poke646/items/w_nailround.mdl
models/poke646/items/w_shotbox.mdl
models/poke646/items/w_shotboxt.mdl
models/poke646/items/w_xencandy.mdl
sound/poke646/buttons/button11.wav
sound/poke646/buttons/lightswitch.wav
sound/poke646/buttons/lightswitch2.wav
sound/poke646/doors/doormove1.wav
maps/po_c2m1.cfg
maps/po_c2m1_motd.txt
maps/po_c2m1_skl.cfg
models/poke646/misc/checkpoint.mdl
sound/poke646/misc/checkpoint.wav
models/poke646/poke646_globalmdl.txt
sound/poke646/poke646_globalsnd.txt
sprites/poke646/po_ammo.spr
sprites/poke646/po_crosshairs.spr
models/player/po_bradshaw/po_bradshaw.mdl
models/player/po_bradshaw/po_bradshaw.bmp
models/player/po_damien/po_damien.mdl
models/player/po_damien/po_damien.bmp
models/player/po_finch/po_finch.mdl
models/player/po_finch/po_finch.bmp
models/player/po_fowley/po_fowley.mdl
models/player/po_fowley/po_fowley.bmp
models/player/po_fuller/po_fuller.mdl
models/player/po_fuller/po_fuller.bmp
models/player/po_hamilton/po_hamilton.mdl
models/player/po_hamilton/po_hamilton.bmp
models/player/po_heinbach/po_heinbach.mdl
models/player/po_heinbach/po_heinbach.bmp
models/player/po_legers/po_legers.mdl
models/player/po_legers/po_legers.bmp
models/player/po_leppard/po_leppard.mdl
models/player/po_leppard/po_leppard.bmp
models/player/po_security/po_security.mdl
models/player/po_security/po_security.bmp
sound/poke646/misc/checkpoint_survival.wav
sound/poke646/misc/checkpoint_close.wav
sound/poke646/misc/checkpoint_pulse.wav
sprites/poke646/muzzleflash3.spr
sprites/poke646/hotglow.spr