// Sven Co-op Map RES file - Poke646 Co-op map
// Map Author:  Mindmotor Studios
// Author Website: http://www.poke646.com/

po_decals.wad
gfx/env/xenbk.tga
gfx/env/xendn.tga
gfx/env/xenft.tga
gfx/env/xenlf.tga
gfx/env/xenrt.tga
gfx/env/xenup.tga
halflife.wad
liquids.wad
models/uplant1.mdl
models/uplant3.mdl
poke646.wad
sound/ambience/alien_creeper.wav
sound/ambience/alien_cycletone.wav
sound/ambience/alienwind2.wav
sound/ambience/genhum.wav
sound/debris/beamstart2.wav
sound/debris/beamstart9.wav
sound/poke646/ambience/xen.wav
sound/poke646/player/bush.wav
sprites/laserbeam.spr
sprites/lgtning.spr
sprites/poke646/glow_lantern.spr
sprites/xspark2.spr
sprites/xspark3.spr
sprites/xspark4.spr
xeno.wad
models/poke646/monsters/scientist/scientist.mdl
maps/po_c5m1.cfg
maps/po_c5m1_motd.txt
maps/po_c5m1_skl.cfg
models/poke646/misc/checkpoint.mdl
models/poke646/poke646_globalmdl.txt
sound/poke646/poke646_globalsnd.txt
sprites/poke646/po_ammo.spr
sprites/poke646/po_crosshairs.spr
sprites/poke646/muzzleflash3.spr
sprites/poke646/hotglow.spr
models/player/po_bradshaw/po_bradshaw.mdl
models/player/po_bradshaw/po_bradshaw.bmp
models/player/po_damien/po_damien.mdl
models/player/po_damien/po_damien.bmp
models/player/po_finch/po_finch.mdl
models/player/po_finch/po_finch.bmp
models/player/po_fowley/po_fowley.mdl
models/player/po_fowley/po_fowley.bmp
models/player/po_fuller/po_fuller.mdl
models/player/po_fuller/po_fuller.bmp
models/player/po_hamilton/po_hamilton.mdl
models/player/po_hamilton/po_hamilton.bmp
models/player/po_heinbach/po_heinbach.mdl
models/player/po_heinbach/po_heinbach.bmp
models/player/po_legers/po_legers.mdl
models/player/po_legers/po_legers.bmp
models/player/po_leppard/po_leppard.mdl
models/player/po_leppard/po_leppard.bmp
models/player/po_security/po_security.mdl
models/player/po_security/po_security.bmp