// Sven Co-op Map RES file - Poke646 Co-op map
// Map Author:  Mindmotor Studios
// Author Website: http://www.poke646.com/

po_decals.wad
gfx/env/po_city_daybk.tga
gfx/env/po_city_daydn.tga
gfx/env/po_city_dayft.tga
gfx/env/po_city_daylf.tga
gfx/env/po_city_dayrt.tga
gfx/env/po_city_dayup.tga
halflife.wad
liquids.wad
poke646.wad
sound/poke646/ambience/city1.wav
sound/poke646/ambience/city2.wav
sound/poke646/ambience/distantmortar2.wav
sound/poke646/ambience/fiep.wav
sound/poke646/ambience/flies.wav
sound/poke646/ambience/mgun_burst1.wav
sound/poke646/ambience/neonlighthum.wav
sound/poke646/ambience/siryessir.wav
sound/poke646/ambience/wren1.wav
sound/poke646/mp3/hazard.mp3
sprites/poke646/levelchange.spr
sprites/yelflare1.spr
sound/poke646/monsters/hgrunt/freeman.wav
sound/poke646/monsters/hgrunt/freeman!.wav
models/poke646/monsters/hgrunt/hgrunt.mdl
models/poke646/monsters/scientist/scientist.mdl
sound/poke646/buttons/button1.wav
sound/poke646/buttons/button11.wav
sound/poke646/buttons/lightswitch.wav
sound/poke646/buttons/lightswitch2.wav
maps/po_c0m1.cfg
maps/po_c0m1_motd.txt
maps/po_c0m1_skl.cfg
models/poke646/poke646_globalmdl.txt
sound/poke646/poke646_globalsnd.txt
sprites/poke646/po_ammo.spr
sprites/poke646/po_crosshairs.spr
sprites/poke646/muzzleflash3.spr
sprites/poke646/hotglow.spr
models/player/po_bradshaw/po_bradshaw.mdl
models/player/po_bradshaw/po_bradshaw.bmp
models/player/po_damien/po_damien.mdl
models/player/po_damien/po_damien.bmp
models/player/po_finch/po_finch.mdl
models/player/po_finch/po_finch.bmp
models/player/po_fowley/po_fowley.mdl
models/player/po_fowley/po_fowley.bmp
models/player/po_fuller/po_fuller.mdl
models/player/po_fuller/po_fuller.bmp
models/player/po_hamilton/po_hamilton.mdl
models/player/po_hamilton/po_hamilton.bmp
models/player/po_heinbach/po_heinbach.mdl
models/player/po_heinbach/po_heinbach.bmp
models/player/po_legers/po_legers.mdl
models/player/po_legers/po_legers.bmp
models/player/po_leppard/po_leppard.mdl
models/player/po_leppard/po_leppard.bmp
models/player/po_security/po_security.mdl
models/player/po_security/po_security.bmp
sound/poke646/misc/checkpoint_survival.wav
sound/poke646/misc/checkpoint_close.wav
sound/poke646/misc/checkpoint_pulse.wav