// Sven Co-op Map RES file - Poke646 Co-op map
// Map Author:  Mindmotor Studios
// Author Website: http://www.poke646.com/

gfx/env/city_nitebk.tga
gfx/env/city_nitedn.tga
gfx/env/city_niteft.tga
gfx/env/city_nitelf.tga
gfx/env/city_nitert.tga
gfx/env/city_niteup.tga
models/poke646/monsters/hgrunt/hgrunt.mdl
models/poke646/props/corpse_female1.mdl
models/poke646/props/corpse_male2.mdl
models/poke646/props/shelf1.mdl
models/poke646/props/shelf2.mdl
models/poke646/props/shelf3.mdl
models/poke646/props/shelf4.mdl
models/poke646/props/trash1.mdl
models/poke646/props/trash2.mdl
models/poke646/props/trash3.mdl
models/vendetta/props/cable1.mdl
models/vendetta/props/generator.mdl
models/vendetta/props/plantpot2.mdl
sound/ambience/alien_beacon.wav
sound/poke646/ambience/city1.wav
sound/poke646/ambience/city2.wav
sound/poke646/ambience/code.wav
sound/poke646/ambience/elevbeep.wav
sound/poke646/ambience/elevbeep2.wav
sound/poke646/ambience/subway.wav
sound/poke646/misc/checkpoint.wav
sound/vendetta/ambience/aircon.wav
sound/vendetta/ambience/alien_spawn2.wav
sound/vendetta/ambience/genhum.wav
sound/vendetta/ambience/machinery1.wav
sound/vendetta/ambience/machinery2.wav
sound/vendetta/ambience/machinery3.wav
sound/vendetta/ambience/neonlighthum.wav
sound/vendetta/ambience/portal_ignition.wav
sound/vendetta/ambience/portal_power.wav
sound/vendetta/ambience/spawn.wav
sound/vendetta/ambience/ssdoor.wav
sound/vendetta/ambience/sstelehum.wav
sound/vendetta/ambience/vent.wav
sound/vendetta/buttons/button1.wav
sound/vendetta/buttons/button10.wav
sound/vendetta/plats/elevstart.wav
sound/vendetta/plats/freightmove2.wav
sprites/e-tele1.spr
sprites/glow01.spr
sprites/poke646/glow_lantern.spr
sprites/vendetta/portal.spr
sprites/yelflare1.spr
maps/poke646_lobby.cfg
maps/poke646_lobby.txt
maps/poke646_lobby.cfg
models/vendetta/vendetta_globalmdl.txt
sound/vendetta/vendetta_globalsnd.txt
models/poke646/poke646_globalmdl.txt
sound/poke646/poke646_globalsnd.txt
sprites/poke646/po_ammo.spr
sprites/vendetta/pv_crosshairs.spr
sprites/vendetta/pv_ammo.spr
sprites/poke646/po_crosshairs.spr
sprites/poke646/muzzleflash3.spr
sprites/poke646/hotglow.spr
models/player/po_bradshaw/po_bradshaw.mdl
models/player/po_bradshaw/po_bradshaw.bmp
models/player/po_damien/po_damien.mdl
models/player/po_damien/po_damien.bmp
models/player/po_finch/po_finch.mdl
models/player/po_finch/po_finch.bmp
models/player/po_fowley/po_fowley.mdl
models/player/po_fowley/po_fowley.bmp
models/player/po_fuller/po_fuller.mdl
models/player/po_fuller/po_fuller.bmp
models/player/po_hamilton/po_hamilton.mdl
models/player/po_hamilton/po_hamilton.bmp
models/player/po_heinbach/po_heinbach.mdl
models/player/po_heinbach/po_heinbach.bmp
models/player/po_legers/po_legers.mdl
models/player/po_legers/po_legers.bmp
models/player/po_leppard/po_leppard.mdl
models/player/po_leppard/po_leppard.bmp
models/player/po_security/po_security.mdl
models/player/po_security/po_security.bmp