// Sven Co-op Map RES file - Poke646: Vendetta Co-op map
// Map Author:  Mindmotor Studios
// Author Website: http://www.poke646.com/

pv_decals.wad
gfx/env/asl_bk.tga
gfx/env/asl_dn.tga
gfx/env/asl_ft.tga
gfx/env/asl_lf.tga
gfx/env/asl_rt.tga
gfx/env/asl_up.tga
models/mil_crategibs.mdl
models/vendetta/monsters/hgrunt/hgrunt.mdl
models/vendetta/misc/crategibs.mdl
models/vendetta/props/spruces.mdl
sound/ambience/alien_frantic.wav
sound/ambience/signalgear1.wav
sound/vendetta/ambience/aircon.wav
sound/vendetta/ambience/alarm.wav
sound/vendetta/ambience/lift.wav
sound/vendetta/ambience/lift_close.wav
sound/vendetta/ambience/lift_open.wav
sound/vendetta/ambience/neonlighthum.wav
sound/vendetta/ambience/tramatmo1.wav
sound/vendetta/ambience/tramatmo2.wav
sound/vendetta/ambience/tramatmo3.wav
sound/vendetta/buttons/liftstart.wav
sound/vendetta/misc/checkpoint.wav
sound/vendetta/mp3/asl.mp3
sprites/glow04.spr
sprites/vendetta/checkpoint.spr
sprites/vendetta/levelchange.spr
sprites/vendetta/tramlight.spr
sprites/yelflare1.spr
vendetta.wad
models/vendetta/weapons/cmlwbr/v_cmlwbr.mdl
models/vendetta/weapons/cmlwbr/w_cmlwbr.mdl
models/vendetta/weapons/cmlwbr/p_cmlwbr.mdl
sound/vendetta/weapons/cmlwbr/cmlwbr_drawback.wav
sound/vendetta/weapons/cmlwbr/cmlwbr_fire.wav
sound/vendetta/weapons/cmlwbr/cmlwbr_reload.wav
sound/vendetta/weapons/cmlwbr/cmlwbr_reload_empty.wav
sound/vendetta/weapons/cmlwbr/cmlwbr_zoom.wav
sprites/vendetta/cmlwbr.spr
sprites/vendetta/weapon_cmlwbr.txt
models/vendetta/weapons/leadpipe/v_leadpipe.mdl
models/vendetta/weapons/leadpipe/w_leadpipe.mdl
models/vendetta/weapons/leadpipe/p_leadpipe.mdl
sound/vendetta/weapons/leadpipe/leadpipe_breathe.wav
sound/vendetta/weapons/leadpipe/leadpipe_hit1.wav
sound/vendetta/weapons/leadpipe/leadpipe_hit2.wav
sound/vendetta/weapons/leadpipe/leadpipe_miss.wav
sprites/vendetta/leadpipe.spr
sprites/vendetta/weapon_leadpipe.txt
models/vendetta/weapons/par21/v_par21.mdl
models/vendetta/weapons/par21/w_par21.mdl
models/vendetta/weapons/par21/p_par21.mdl
sound/vendetta/weapons/par21/par21_fire.wav
sound/vendetta/weapons/par21/par21_gl1.wav
sound/vendetta/weapons/par21/par21_gl2.wav
sound/vendetta/weapons/par21/par21_reload.wav
sprites/vendetta/par21.spr
sprites/vendetta/weapon_par21.txt
models/vendetta/weapons/sawedoff/v_sawedoff.mdl
models/vendetta/weapons/sawedoff/w_sawedoff.mdl
models/vendetta/weapons/sawedoff/p_sawedoff.mdl
sound/vendetta/weapons/sawedoff/sawedoff_fire.wav
sound/vendetta/weapons/sawedoff/sawedoff_pump.wav
sound/vendetta/weapons/sawedoff/sawedoff_reload1.wav
sound/vendetta/weapons/sawedoff/sawedoff_reload2.wav
sprites/vendetta/sawedoff.spr
sprites/vendetta/weapon_sawedoff.txt
sound/vendetta/buttons/blip1.wav
sound/vendetta/buttons/blip2.wav
sound/vendetta/buttons/button1.wav
sound/vendetta/buttons/button7.wav
sound/vendetta/buttons/button8.wav
sound/vendetta/buttons/button10.wav
sound/vendetta/buttons/button11.wav
sound/vendetta/buttons/spark1.wav
sound/vendetta/buttons/spark2.wav
sound/vendetta/buttons/spark3.wav
sound/vendetta/buttons/spark4.wav
sound/vendetta/buttons/spark5.wav
sound/vendetta/buttons/spark6.wav
sound/vendetta/buttons/doormove1.wav
sound/vendetta/plats/freightmove1.wav
sound/vendetta/plats/freightmove2.wav
sound/vendetta/plats/train_use1.wav
sound/vendetta/plats/train_brake1.wav
sound/vendetta/plats/ttrain1.wav
models/vendetta/items/crossbow_bolt.mdl
models/vendetta/items/grenade.mdl
models/vendetta/items/nail.mdl
models/vendetta/items/shotgunshell.mdl
models/vendetta/items/w_crossbow_clip.mdl
models/vendetta/items/w_medibox.mdl
models/vendetta/items/w_par21_clip.mdl
models/vendetta/items/w_par21_grenades.mdl
models/vendetta/items/w_par21_grenadest.mdl
models/vendetta/items/w_shotbox.mdl
models/vendetta/items/w_shotboxt.mdl
maps/pv_c2m5.cfg
maps/pv_c2m5_motd.txt
maps/pv_c2m5_skl.cfg
models/vendetta/misc/checkpoint.mdl
sound/vendetta/vendetta_globalsnd.txt
models/vendetta/vendetta_globalmdl.txt
sound/vendetta/buttons/fuse.wav
sprites/vendetta/pv_ammo.spr
sprites/vendetta/pv_crosshairs.spr
models/player/po_bradshaw/po_bradshaw.mdl
models/player/po_bradshaw/po_bradshaw.bmp
models/player/po_damien/po_damien.mdl
models/player/po_damien/po_damien.bmp
models/player/po_finch/po_finch.mdl
models/player/po_finch/po_finch.bmp
models/player/po_fowley/po_fowley.mdl
models/player/po_fowley/po_fowley.bmp
models/player/po_fuller/po_fuller.mdl
models/player/po_fuller/po_fuller.bmp
models/player/po_hamilton/po_hamilton.mdl
models/player/po_hamilton/po_hamilton.bmp
models/player/po_heinbach/po_heinbach.mdl
models/player/po_heinbach/po_heinbach.bmp
models/player/po_legers/po_legers.mdl
models/player/po_legers/po_legers.bmp
models/player/po_leppard/po_leppard.mdl
models/player/po_leppard/po_leppard.bmp
models/player/po_security/po_security.mdl
models/player/po_security/po_security.bmp
sound/vendetta/misc/checkpoint_survival.wav
sound/vendetta/misc/checkpoint_close.wav
sound/vendetta/misc/checkpoint_pulse.wav