// Sven Co-op Map RES file - Poke646: Vendetta Co-op map
// Map Author:  Mindmotor Studios
// Author Website: http://www.vendetta.com/

pv_decals.wad
models/vendetta/props/cable2.mdl
models/vendetta/props/cable4.mdl
models/vendetta/props/diag_monitor.mdl
models/vendetta/props/flashlight.mdl
models/vendetta/props/switch_vent.mdl
models/vendetta/props/techtools.mdl
models/vendetta/props/teleportfx.mdl
sound/ambience/alien_blipper.wav
sound/ambience/alien_frantic.wav
sound/ambience/rocket_groan1.wav
sound/ambience/rocket_groan2.wav
sound/ambience/rocket_groan3.wav
sound/ambience/rocket_groan4.wav
sound/vendetta/ambience/advice.wav
sound/vendetta/ambience/cs_plasma.wav
sound/vendetta/ambience/cs_welcome.wav
sound/vendetta/ambience/flicker.wav
sound/vendetta/ambience/lift.wav
sound/vendetta/ambience/neonlighthum.wav
sound/vendetta/ambience/spawn.wav
sound/vendetta/ambience/sscompbleep.wav
sound/vendetta/ambience/ssdoor.wav
sound/vendetta/ambience/ssshutdown.wav
sound/vendetta/ambience/sstelehum.wav
sound/vendetta/ambience/vent_hydraulics.wav
sound/vendetta/buttons/liftstart.wav
sound/vendetta/buttons/medical_treatment.wav
sound/vendetta/ui/laptop_loop.wav
sound/vendetta/ui/laptop_off.wav
sound/vendetta/mp3/orl.mp3
sprites/e-tele1.spr
sprites/glow04.spr
sprites/laserbeam.spr
sprites/vendetta/flashlight.spr
sprites/vendetta/glow_lantern.spr
sprites/vendetta/levelchange.spr
sprites/xflare1.spr
sprites/yelflare1.spr
vendetta.wad
models/vendetta/weapons/leadpipe/v_leadpipe.mdl
models/vendetta/weapons/leadpipe/w_leadpipe.mdl
models/vendetta/weapons/leadpipe/p_leadpipe.mdl
sound/vendetta/weapons/leadpipe/leadpipe_breathe.wav
sound/vendetta/weapons/leadpipe/leadpipe_hit1.wav
sound/vendetta/weapons/leadpipe/leadpipe_hit2.wav
sound/vendetta/weapons/leadpipe/leadpipe_miss.wav
sprites/vendetta/leadpipe.spr
sprites/vendetta/weapon_leadpipe.txt
models/vendetta/monsters/scientist/scientist.mdl
sound/vendetta/buttons/blip1.wav
sound/vendetta/buttons/blip2.wav
sound/vendetta/buttons/button1.wav
sound/vendetta/buttons/button7.wav
sound/vendetta/buttons/button8.wav
sound/vendetta/buttons/button10.wav
sound/vendetta/buttons/button11.wav
sound/vendetta/buttons/spark1.wav
sound/vendetta/buttons/spark2.wav
sound/vendetta/buttons/spark3.wav
sound/vendetta/buttons/spark4.wav
sound/vendetta/buttons/spark5.wav
sound/vendetta/buttons/spark6.wav
sound/vendetta/buttons/doormove1.wav
sound/vendetta/plats/freightmove1.wav
sound/vendetta/plats/freightmove2.wav
sound/vendetta/plats/train_use1.wav
sound/vendetta/plats/train_brake1.wav
sound/vendetta/plats/ttrain1.wav
models/vendetta/items/crossbow_bolt.mdl
models/vendetta/items/grenade.mdl
models/vendetta/items/nail.mdl
models/vendetta/items/shotgunshell.mdl
models/vendetta/items/w_crossbow_clip.mdl
models/vendetta/items/w_medibox.mdl
models/vendetta/items/w_par21_clip.mdl
models/vendetta/items/w_par21_grenades.mdl
models/vendetta/items/w_par21_grenadest.mdl
models/vendetta/items/w_shotbox.mdl
models/vendetta/items/w_shotboxt.mdl
maps/pv_c1m1.cfg
maps/pv_c1m1_motd.txt
maps/pv_c1m1_skl.cfg
models/vendetta/misc/checkpoint.mdl
sound/vendetta/misc/checkpoint.wav
sound/vendetta/vendetta_globalsnd.txt
models/vendetta/vendetta_globalmdl.txt
sound/vendetta/buttons/fuse.wav
sprites/vendetta/pv_ammo.spr
sprites/vendetta/pv_crosshairs.spr
models/player/po_bradshaw/po_bradshaw.mdl
models/player/po_bradshaw/po_bradshaw.bmp
models/player/po_damien/po_damien.mdl
models/player/po_damien/po_damien.bmp
models/player/po_finch/po_finch.mdl
models/player/po_finch/po_finch.bmp
models/player/po_fowley/po_fowley.mdl
models/player/po_fowley/po_fowley.bmp
models/player/po_fuller/po_fuller.mdl
models/player/po_fuller/po_fuller.bmp
models/player/po_hamilton/po_hamilton.mdl
models/player/po_hamilton/po_hamilton.bmp
models/player/po_heinbach/po_heinbach.mdl
models/player/po_heinbach/po_heinbach.bmp
models/player/po_legers/po_legers.mdl
models/player/po_legers/po_legers.bmp
models/player/po_leppard/po_leppard.mdl
models/player/po_leppard/po_leppard.bmp
models/player/po_security/po_security.mdl
models/player/po_security/po_security.bmp
sound/vendetta/misc/checkpoint_survival.wav
sound/vendetta/misc/checkpoint_close.wav
sound/vendetta/misc/checkpoint_pulse.wav