// Sven Co-op Map RES file - Poke646: Vendetta Co-op map
// Map Author:  Mindmotor Studios
// Author Website: http://www.vendetta.com/

pv_decals.wad
gfx/env/orl_bk.tga
gfx/env/orl_dn.tga
gfx/env/orl_ft.tga
gfx/env/orl_lf.tga
gfx/env/orl_rt.tga
gfx/env/orl_up.tga
models/leech.mdl
models/mil_crategibs.mdl
models/vendetta/props/3dchess.mdl
models/vendetta/props/armory1.mdl
models/vendetta/props/armory2.mdl
models/vendetta/props/armyknife.mdl
models/vendetta/props/cable1.mdl
models/vendetta/props/cable2.mdl
models/vendetta/props/can.mdl
models/vendetta/props/chair.mdl
models/vendetta/props/coupler.mdl
models/vendetta/props/evidence.mdl
models/vendetta/props/flasks.mdl
models/vendetta/props/folder.mdl
models/vendetta/props/folder_open.mdl
models/vendetta/props/heatstand.mdl
models/vendetta/props/microscope.mdl
models/vendetta/props/military.mdl
models/vendetta/props/space_tourist.mdl
models/vendetta/props/techtools.mdl
models/vendetta/props/toilet.mdl
models/vendetta/props/transponder.mdl
models/vendetta/props/washbasin.mdl
sound/ambience/signalgear1.wav
sound/vendetta/ambience/advice.wav
sound/vendetta/ambience/aircon.wav
sound/vendetta/ambience/alien_chatter.wav
sound/vendetta/ambience/curtain.wav
sound/vendetta/ambience/flicker.wav
sound/vendetta/ambience/fusion_reactor1.wav
sound/vendetta/ambience/ipanema.wav
sound/vendetta/ambience/magnet_hum.wav
sound/vendetta/ambience/neonlighthum.wav
sound/vendetta/ambience/pickup_card.wav
sound/vendetta/ambience/plasma_pump.wav
sound/vendetta/ambience/sscompbleep.wav
sound/vendetta/ambience/ssdoor.wav
sound/vendetta/buttons/medical_treatment.wav
sound/vendetta/ui/laptop_loop.wav
sound/vendetta/ui/laptop_off.wav
sprites/glow01.spr
sprites/glow04.spr
sprites/lgtning.spr
sprites/vendetta/levelchange.spr
sprites/yelflare1.spr
vendetta.wad
models/vendetta/weapons/cmlwbr/v_cmlwbr.mdl
models/vendetta/weapons/cmlwbr/w_cmlwbr.mdl
models/vendetta/weapons/cmlwbr/p_cmlwbr.mdl
sound/vendetta/weapons/cmlwbr/cmlwbr_drawback.wav
sound/vendetta/weapons/cmlwbr/cmlwbr_fire.wav
sound/vendetta/weapons/cmlwbr/cmlwbr_reload.wav
sound/vendetta/weapons/cmlwbr/cmlwbr_reload_empty.wav
sound/vendetta/weapons/cmlwbr/cmlwbr_zoom.wav
sprites/vendetta/cmlwbr.spr
sprites/vendetta/weapon_cmlwbr.txt
models/vendetta/weapons/leadpipe/v_leadpipe.mdl
models/vendetta/weapons/leadpipe/w_leadpipe.mdl
models/vendetta/weapons/leadpipe/p_leadpipe.mdl
sound/vendetta/weapons/leadpipe/leadpipe_breathe.wav
sound/vendetta/weapons/leadpipe/leadpipe_hit1.wav
sound/vendetta/weapons/leadpipe/leadpipe_hit2.wav
sound/vendetta/weapons/leadpipe/leadpipe_miss.wav
sprites/vendetta/leadpipe.spr
sprites/vendetta/weapon_leadpipe.txt
models/vendetta/weapons/par21/v_par21.mdl
models/vendetta/weapons/par21/w_par21.mdl
models/vendetta/weapons/par21/p_par21.mdl
sound/vendetta/weapons/par21/par21_fire.wav
sound/vendetta/weapons/par21/par21_gl1.wav
sound/vendetta/weapons/par21/par21_gl2.wav
sound/vendetta/weapons/par21/par21_reload.wav
sprites/vendetta/par21.spr
sprites/vendetta/weapon_par21.txt
models/vendetta/monsters/scientist/scientist.mdl
models/vendetta/monsters/hgrunt/hgrunt.mdl
sound/vendetta/buttons/blip1.wav
sound/vendetta/buttons/blip2.wav
sound/vendetta/buttons/button1.wav
sound/vendetta/buttons/button7.wav
sound/vendetta/buttons/button8.wav
sound/vendetta/buttons/button10.wav
sound/vendetta/buttons/button11.wav
sound/vendetta/buttons/spark1.wav
sound/vendetta/buttons/spark2.wav
sound/vendetta/buttons/spark3.wav
sound/vendetta/buttons/spark4.wav
sound/vendetta/buttons/spark5.wav
sound/vendetta/buttons/spark6.wav
sound/vendetta/buttons/doormove1.wav
sound/vendetta/plats/freightmove1.wav
sound/vendetta/plats/freightmove2.wav
sound/vendetta/plats/train_use1.wav
sound/vendetta/plats/train_brake1.wav
sound/vendetta/plats/ttrain1.wav
models/vendetta/items/crossbow_bolt.mdl
models/vendetta/items/grenade.mdl
models/vendetta/items/nail.mdl
models/vendetta/items/shotgunshell.mdl
models/vendetta/items/w_crossbow_clip.mdl
models/vendetta/items/w_medibox.mdl
models/vendetta/items/w_par21_clip.mdl
models/vendetta/items/w_par21_grenades.mdl
models/vendetta/items/w_par21_grenadest.mdl
models/vendetta/items/w_shotbox.mdl
models/vendetta/items/w_shotboxt.mdl
maps/pv_c1m4.cfg
maps/pv_c1m4_motd.txt
maps/pv_c1m4_skl.cfg
models/vendetta/misc/checkpoint.mdl
sound/vendetta/misc/checkpoint.wav
sound/vendetta/vendetta_globalsnd.txt
models/vendetta/vendetta_globalmdl.txt
sound/vendetta/buttons/fuse.wav
sprites/vendetta/pv_ammo.spr
sprites/vendetta/pv_crosshairs.spr
models/player/po_bradshaw/po_bradshaw.mdl
models/player/po_bradshaw/po_bradshaw.bmp
models/player/po_damien/po_damien.mdl
models/player/po_damien/po_damien.bmp
models/player/po_finch/po_finch.mdl
models/player/po_finch/po_finch.bmp
models/player/po_fowley/po_fowley.mdl
models/player/po_fowley/po_fowley.bmp
models/player/po_fuller/po_fuller.mdl
models/player/po_fuller/po_fuller.bmp
models/player/po_hamilton/po_hamilton.mdl
models/player/po_hamilton/po_hamilton.bmp
models/player/po_heinbach/po_heinbach.mdl
models/player/po_heinbach/po_heinbach.bmp
models/player/po_legers/po_legers.mdl
models/player/po_legers/po_legers.bmp
models/player/po_leppard/po_leppard.mdl
models/player/po_leppard/po_leppard.bmp
models/player/po_security/po_security.mdl
models/player/po_security/po_security.bmp
sound/vendetta/misc/checkpoint_survival.wav
sound/vendetta/misc/checkpoint_close.wav
sound/vendetta/misc/checkpoint_pulse.wav