// Sven Co-op Map RES file - Poke646: Vendetta Co-op map
// Map Author:  Mindmotor Studios
// Author Website: http://www.poke646.com/

pv_decals.wad
gfx/env/xen_bk.tga
gfx/env/xen_dn.tga
gfx/env/xen_ft.tga
gfx/env/xen_lf.tga
gfx/env/xen_rt.tga
gfx/env/xen_up.tga
models/vendetta/monsters/robocop.mdl
models/vendetta/monsters/scientist/scientist.mdl
models/vendetta/props/cable3.mdl
models/vendetta/props/techtools.mdl
sound/ambience/alienwind2.wav
sound/vendetta/ambience/alien_spawn2.wav
sound/vendetta/ambience/computer.wav
sound/vendetta/ambience/neonlighthum.wav
sound/vendetta/ambience/portal_ignition.wav
sound/vendetta/ambience/portal_power.wav
sound/vendetta/ambience/sstelehum.wav
sound/vendetta/buttons/fuse.wav
sound/vendetta/mp3/int.mp3
sprites/e-tele1.spr
sprites/lgtning.spr
sprites/vendetta/fire.spr
sprites/vendetta/intro01.spr
sprites/vendetta/intro02.spr
sprites/vendetta/intro03.spr
sprites/vendetta/portal.spr
sprites/yelflare1.spr
vendetta.wad
models/vendetta/monsters/robocop/robocop.mdl
models/vendetta/monsters/scientist/scientist.mdl
maps/pv_intro.cfg
maps/pv_intro_motd.txt
maps/pv_intro_skl.cfg
sound/vendetta/vendetta_globalsnd.txt
models/vendetta/vendetta_globalmdl.txt
sprites/vendetta/pv_ammo.spr
sprites/vendetta/pv_crosshairs.spr
models/player/po_bradshaw/po_bradshaw.mdl
models/player/po_bradshaw/po_bradshaw.bmp
models/player/po_damien/po_damien.mdl
models/player/po_damien/po_damien.bmp
models/player/po_finch/po_finch.mdl
models/player/po_finch/po_finch.bmp
models/player/po_fowley/po_fowley.mdl
models/player/po_fowley/po_fowley.bmp
models/player/po_fuller/po_fuller.mdl
models/player/po_fuller/po_fuller.bmp
models/player/po_hamilton/po_hamilton.mdl
models/player/po_hamilton/po_hamilton.bmp
models/player/po_heinbach/po_heinbach.mdl
models/player/po_heinbach/po_heinbach.bmp
models/player/po_legers/po_legers.mdl
models/player/po_legers/po_legers.bmp
models/player/po_leppard/po_leppard.mdl
models/player/po_leppard/po_leppard.bmp
models/player/po_security/po_security.mdl
models/player/po_security/po_security.bmp
sound/vendetta/misc/checkpoint_survival.wav
sound/vendetta/misc/checkpoint_close.wav
sound/vendetta/misc/checkpoint_pulse.wav
sound/vendetta/buttons/spark1.wav
sound/vendetta/buttons/spark2.wav
sound/vendetta/buttons/spark3.wav
sound/vendetta/buttons/spark4.wav
sound/vendetta/buttons/spark5.wav
sound/vendetta/buttons/spark6.wav