// Sven Co-op Map RES file - Poke646: Vendetta Co-op map
// Map Author:  Mindmotor Studios
// Author Website: http://www.poke646.com/

pv_decals.wad
gfx/env/out_bk.tga
gfx/env/out_dn.tga
gfx/env/out_ft.tga
gfx/env/out_lf.tga
gfx/env/out_rt.tga
gfx/env/out_up.tga
models/vendetta/props/can.mdl
models/vendetta/props/chair.mdl
models/vendetta/props/computer.mdl
models/vendetta/props/folder.mdl
models/vendetta/props/folder_open.mdl
models/vendetta/props/plantpot1.mdl
models/vendetta/props/plantpot2.mdl
models/vendetta/props/techtools.mdl
sound/vendetta/ambience/computer.wav
sound/vendetta/ambience/elevbeep.wav
sound/vendetta/ambience/elevbeep2.wav
sound/vendetta/ambience/gman.wav
sound/vendetta/ambience/neonlighthum.wav
sprites/vendetta/glow_lantern.spr
sound/vendetta/mp3/out.mp3
vendetta.wad
models/vendetta/monsters/gman/gman.mdl
models/vendetta/monsters/scientist/scientist.mdl
maps/pv_outro.cfg
maps/pv_outro_motd.txt
maps/pv_outro_skl.cfg
sound/vendetta/vendetta_globalsnd.txt
models/vendetta/vendetta_globalmdl.txt
sprites/vendetta/pv_ammo.spr
sprites/vendetta/pv_crosshairs.spr
models/player/po_bradshaw/po_bradshaw.mdl
models/player/po_bradshaw/po_bradshaw.bmp
models/player/po_damien/po_damien.mdl
models/player/po_damien/po_damien.bmp
models/player/po_finch/po_finch.mdl
models/player/po_finch/po_finch.bmp
models/player/po_fowley/po_fowley.mdl
models/player/po_fowley/po_fowley.bmp
models/player/po_fuller/po_fuller.mdl
models/player/po_fuller/po_fuller.bmp
models/player/po_hamilton/po_hamilton.mdl
models/player/po_hamilton/po_hamilton.bmp
models/player/po_heinbach/po_heinbach.mdl
models/player/po_heinbach/po_heinbach.bmp
models/player/po_legers/po_legers.mdl
models/player/po_legers/po_legers.bmp
models/player/po_leppard/po_leppard.mdl
models/player/po_leppard/po_leppard.bmp
models/player/po_security/po_security.mdl
models/player/po_security/po_security.bmp
sound/vendetta/misc/checkpoint_survival.wav
sound/vendetta/misc/checkpoint_close.wav
sound/vendetta/misc/checkpoint_pulse.wav